// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodel

type NewService struct {
	Name string `json:"name"`
}

type Service struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
