services:

  nginx:
    build:
      context: .
      dockerfile: nginx/production/Dockerfile
    links:
      - php-fpm
    ports:
      - 8080:80

  php-fpm:
    build:
      context: .
      dockerfile: slim/production/Dockerfile
    links:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis
    ports:
        - 6379:6379

  # phpunit:
  #   build: php-fpm/
  #   volumes:
  #     - .:/var/www/html
  #   links:
  #     - redis
  #     - nginx
  #   environment:
  #     - REDIS_HOST=redis

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus-data:
