version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: dev.Dockerfile
    volumes:
      - ./ui/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      next-js:
        condition: service_started
      graphql:
        condition: service_started
    networks:
      - public-network
    ports:
      - "80:80"
    environment:
      - NGINX_INVMAN_AUTH_HOST=${INVMAN_AUTH_HOST}
      - NGINX_INVMAN_APP_HOST=${INVMAN_APP_HOST}
      - NGINX_INVMAN_API_HOST=${INVMAN_API_HOST}
      - NGINX_INVMAN_NEXT_JS_HOST=http://next-js:3000 #todo
      - NGINX_INVMAN_GRAPHQL_HOST=http://graphql:8080 #todo
      - NGINX_INVMAN_AUTH_APP_HOST=http://auth-app:8080 #todo

  next-js:
    container_name: next-js
    build:
      context: ./next-js
      dockerfile: docker/dev.Dockerfile
    volumes:
      - ./next-js/src:/app/src
      - ./next-js/public:/app/public
    networks:
      - public-network
    depends_on:
      auth-app:
        condition: service_started
      graphql:
        condition: service_started
    environment:
      - NEXTAUTH_URL=${INVMAN_APP_URL}/api/auth
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_INVMAN_CLIENT_ID=${INVMAN_AUTH_CLIENT_ID}
      - NEXTAUTH_INVMAN_CLIENT_SECRET=${INVMAN_AUTH_CLIENT_SECRET}
      - INVMAN_AUTH_URL=${INVMAN_AUTH_URL}
      - NEXT_PUBLIC_INVMAN_API_URL=${INVMAN_API_URL}

  graphql:
    container_name: graphql
    build:
      context: ./graphql
      dockerfile: dev.Dockerfile
    volumes:
      - ./graphql:/app
    networks:
      - public-network
      - service-network
    depends_on:
      service-postgres:
        condition: service_healthy
    environment:
      - TOKEN_SECRET=${INVMAN_ACCESS_TOKEN_SECRET}
      - INVMAN_APP_URL=${INVMAN_APP_URL}
      - DATABASE_HOST=service-postgres
      - DATABASE_USER=${SERVICE_POSTGRES_USER}
      - DATABASE_PASSWORD=${SERVICE_POSTGRES_PASSWORD}
      - DATABASE_PORT=${SERVICE_POSTGRES_PORT}
      - DATABASE_NAME=${SERVICE_POSTGRES_NAME}

  auth-app:
    container_name: auth-app
    build:
      context: ./services/auth/app
      dockerfile: dev.Dockerfile
    volumes:
      - ./services/auth/app:/app
    depends_on:
      auth-redis:
        condition: service_started
      auth-postgres:
        condition: service_healthy
    networks:
      - public-network
      - auth-network
    environment:
      - CLIENT_ID=${INVMAN_AUTH_CLIENT_ID}
      - CLIENT_SECRET=${INVMAN_AUTH_CLIENT_SECRET}
      - TOKEN_SECRET=${INVMAN_ACCESS_TOKEN_SECRET}
      - INVMAN_APP_URL=${INVMAN_APP_URL}
      - INVMAN_AUTH_URL=${INVMAN_AUTH_URL}
      - DATABASE_HOST=auth-postgres
      - DATABASE_USER=${AUTH_POSTGRES_USER}
      - DATABASE_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - DATABASE_PORT=${AUTH_POSTGRES_PORT}
      - DATABASE_NAME=${AUTH_POSTGRES_NAME}
      - REDIS_HOST=auth-redis:6379

  auth-redis:
    container_name: auth-redis
    image: "redis:alpine"
    # command: redis-server --requirepass sOmE_sEcUrE_pAsS
    volumes:
      - ./services/auth/redis/data:/var/lib/redis
      # - ./services/oauth/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - auth-network

  auth-postgres:
    container_name: auth-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
    volumes:
      - ./services/auth/pg/data:/var/lib/postgresql/data
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${AUTH_POSTGRES_PASSWORD}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  service-postgres:
    container_name: service-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${SERVICE_POSTGRES_PASSWORD}
    volumes:
      - ./services/service/pg/data:/var/lib/postgresql/data
    networks:
      - service-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${SERVICE_POSTGRES_PASSWORD}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - auth-network

networks:
  public-network:
  auth-network:
  service-network: 