version: '3'

services:

  # HTTP proxy
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: nginx/prod.Dockerfile
    restart: always
    networks:
      - public-network
    # depends_on:
    #   - item-api
    ports:
      - "80:80"

  # Web app
  next-js:
    env_file:
      - .env.prod
    container_name: next-js
    build:
      context: ./next-js
      dockerfile: prod.Dockerfile
    restart: always
    networks:
      - public-network

  # Graph
  graphql:
    container_name: graphql
    build:
      context: ./graphql
      dockerfile: prod.Dockerfile
    restart: always
    networks:
      - public-network
      - service-network

  # Service-api
  service-api:
    container_name: service-api
    build:
      context: ./service-api/app
      dockerfile: prod.Dockerfile
    restart: always
    networks:
      - service-network

  service-db:
    container_name: service-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: EsOieQ8V4
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - service-network
volumes:
  pgdata:

networks:
  public-network:
  service-network:


