version: '3'

services:

  # HTTP proxy
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./next-js/:/var/www/html/
    #   - ./item-api/logs/nginx:/var/log/nginx/
    networks:
      - frontend-network
    # depends_on:
    #   - item-api
    ports:
      - "80:80"

  next-js:
    container_name: next-js
    build:
      context: ./next-js
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./next-js/src:/app/src
      - ./next-js/public:/app/public
    restart: always
    networks:
      - frontend-network

networks:
  frontend-network:


