version: '3'

services:

  # HTTP proxy
  item-api-proxy:
    container_name: item-api-proxy
    build:
      context: ./item-api/nginx
      dockerfile: Dockerfile
    volumes:
      - ./item-api/slim/:/var/www/html/
      - ./item-api/logs/nginx:/var/log/nginx/
    networks:
      - internal-network
    depends_on:
      - item-api
    ports:
      - "8080:80"
    # profiles:
    #   - item-api

    # API
  item-api:
    container_name: item-api
    build:
      context: ./item-api/slim
      dockerfile: config/develop/dev.Dockerfile
    volumes:
      - ./item-api/slim/:/var/www/html
    networks:
      - internal-network
      - database-network
    # profiles:
    #   - item-api
    depends_on:
      - item-api-database-metrics
      - item-api-database
    environment:
      - PHP_IDE_CONFIG=serverName=item-api
      - REDIS_HOST=item-api-database-metrics
      - DATABASE_HOST=item-api-database
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=example # TODO Change to something more secure
    command: sh -c "composer install | php-fpm" # Autoload files | run server
    extra_hosts:
      - host.docker.internal:host-gateway

  # Database
  item-api-database:
    container_name: item-api-database
    image: postgres
    networks:
      - database-network
    environment:
      POSTGRES_PASSWORD: example

  # Database manager
  item-api-db-manager:
    container_name: item-api-db-manager
    image: adminer
    networks:
      - database-network
    ports:
      - 8081:8080

  # Api statistics storage (analytics)
  item-api-database-metrics:
    container_name: item-api-database-metrics
    image: redis
    networks:
      - internal-network
    # profiles:
    #   - item-api

    # Proxy statistics scraper (analytics)
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.8.0
    depends_on:
      - item-api-proxy
    networks:
      - internal-network
    command:
      - -nginx.scrape-uri
      - http://item-api-proxy:10021/stub_status

  # Analytics
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.30.3
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - internal-network
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus-data:


networks:
  internal-network:
  database-network:


