version: '3'

services:

  # HTTP proxy
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./next-js/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    networks:
      - public-network
    # depends_on:
    #   - item-api
    ports:
      - "80:80"

  # Web app
  next-js:
    env_file:
      - .env.dev
    container_name: next-js
    build:
      context: ./next-js
      dockerfile: dev.Dockerfile
    volumes:
      - ./next-js/src:/app/src
      - ./next-js/public:/app/public
    restart: always
    networks:
      - public-network

  # Service-api
  graphql:
    container_name: graphql
    build:
      context: ./graphql
      dockerfile: dev.Dockerfile
    restart: always
    volumes:
      - ./graphql:/app
    networks:
      - public-network
      - service-network
    ports:
      - 8081:8080

  # Service-api
  service-api:
    container_name: service-api
    build:
      context: ./service-api/app
      dockerfile: dev.Dockerfile
    restart: always
    volumes:
      - ./service-api/app:/app
    networks:
      - service-network
    ports:
      - 8082:8080

  service-db:
    container_name: service-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./service-api/pg:/var/lib/postgresql/data
    networks:
      - service-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - service-network

networks:
  public-network:
  service-network:


