version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: docker/prod.Dockerfile
    restart: always
    volumes:
      - ./logs/nginx:/var/log/nginx/
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    networks:
      - general-network
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 10s
      timeout: 3s
      retries: 3

  mail:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mail
    hostname: mail.invman.nl
    environment:
      - SSL_TYPE=letsencrypt
      - ENABLE_FAIL2BAN=1
      - ENABLE_RSPAMD=1
      - ENABLE_OPENDKIM=0
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./mail/data/:/var/mail/
      - ./mail/state/:/var/mail-state/
      - ./mail/config/:/tmp/docker-mailserver/
      - ./logs/mail/:/var/log/mail/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "25:25" # SMTP  (explicit TLS => STARTTLS)
      - "143:143" # IMAP4 (explicit TLS => STARTTLS)
      - "465:465" # ESMTP (implicit TLS)
      - "587:587" # ESMTP (explicit TLS => STARTTLS)
      - "993:993" # IMAP4 (implicit TLS)
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  general-network:


volumes:
  prometheus_data:
  monitor_data:
