global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-metrics-exporter:9113']

  - job_name: 'app'
    static_configs:
      - targets: ['app:3000']

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:8080']
    
  - job_name: 'api'
    static_configs:
      - targets: ['api:8080']
