global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'slim-microservice'
    static_configs:
      - targets: ['nginx:80']