// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph_model

type NewService struct {
	Name string `json:"name"`
}

type Service struct {
	UUID      string `json:"uuid"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type UpdateService struct {
	UUID string `json:"uuid"`
	Name string `json:"name"`
}
