// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type CreateItemInput struct {
	Attributes *ItemAttributesInput `json:"attributes,omitempty"`
}

type Item struct {
	ID         uuid.UUID       `json:"id"`
	GroupID    *uuid.UUID      `json:"groupId,omitempty"`
	Attributes *ItemAttributes `json:"attributes"`
	CreatedAt  time.Time       `json:"createdAt"`
	UpdatedAt  *time.Time      `json:"updatedAt,omitempty"`
}

type ItemAttributeField struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Type  string    `json:"type"`
	Value string    `json:"value"`
}

type ItemAttributes struct {
	Fields []ItemAttributeField `json:"fields,omitempty"`
}

type ItemAttributesFieldInput struct {
	Name  string `json:"name"`
	Type  string `json:"type"`
	Value string `json:"value"`
}

type ItemAttributesInput struct {
	Fields []ItemAttributesFieldInput `json:"fields,omitempty"`
}

type ItemsInput struct {
	Limit  int  `json:"limit"`
	Offset *int `json:"offset,omitempty"`
}
